//add user's input to list item 
const addNames = function(){
    //target user input
    let newName = document.getElementById("newName").value
    //creating new empty list item
    let newItem = document.createElement("li")
    //assign new name to the empty list
    newItem.innerHTML = newName
    //target the parent container of the list item
    let nameContainer = document.querySelector(".nameListContainer")
    //assign new value into the parent container
    nameContainer.append(newItem)
}

const clearNames = function(){
    //target all list items
    let allListItems = document.querySelectorAll("li")
    for (item of allListItems){
        item.outerHTML = ""
    }
}

// const playingAgainst1Team = function(){
//     const buttonClicked = document.getElementById("button1")
//     buttonClicked.addEventListener("clicked", function(){
//         //let user know how many teams they are playing against
//         let numberOfTeams = document.getElementsById("teamsPlayingPreview")
//         numberOfTeams.innerHTML = "You are playing against 1 Team"
//     })
// } 
//!! need to figure out how to add event listener properly

const playingAgainstOneTeam = function(){
    let numberOfTeams = document.getElementById("teamsPlayingPreview")
    // console.log(numberOfTeams)
    numberOfTeams.innerHTML = "You are playing against 1 Team"
    console.log(numberOfTeams)
}

const playingAgainstTwoTeam = function(){
    let numberOfTeams = document.getElementById("teamsPlayingPreview")
    // console.log(numberOfTeams)
    numberOfTeams.innerHTML = "You are playing against 2 Teams"
    console.log(numberOfTeams)
}

const playingAgainstThreeTeam = function(){
    let numberOfTeams = document.getElementById("teamsPlayingPreview")
    // console.log(numberOfTeams)
    numberOfTeams.innerHTML = "You are playing against 3 Teams"
    console.log(numberOfTeams)
}



// const assignNamesToGroups = function(){
//     //get the array of Names generated by users
//     let getAllNames = document.querySelectorAll("li")
//     for (names of getAllNames){
//         console.log(names)
//     }
// }

