//add user's input to list item 
const addNames = function(){
    //target user input
    let newName = document.getElementById("newName").value
    //creating new empty list item
    let newItem = document.createElement("li")
    //assign new name to the empty list
    newItem.innerHTML = newName
    //target the parent container of the list item
    let nameContainer = document.querySelector(".nameListContainer")
    //assign new value into the parent container
    nameContainer.append(newItem)
}

const clearNames = function(){
    //target all list items
    let allListItems = document.querySelectorAll("li")
    for (item of allListItems){
        item.outerHTML = ""
    }
}

// const playingAgainst1Team = function(){
//     const buttonClicked = document.getElementById("button1")
//     buttonClicked.addEventListener("clicked", function(){
//         //let user know how many teams they are playing against
//         let numberOfTeams = document.getElementsById("teamsPlayingPreview")
//         numberOfTeams.innerHTML = "You are playing against 1 Team"
//     })
// } 
//!! need to figure out how to add event listener properly

const playingAgainstOneTeam = function(){
    let numberOfTeams = document.getElementById("teamsPlayingPreview")
    // console.log(numberOfTeams)
    numberOfTeams.innerHTML = "You are playing against 1 Team"
    console.log(numberOfTeams)
}

const playingAgainstTwoTeam = function(){
    let numberOfTeams = document.getElementById("teamsPlayingPreview")
    // console.log(numberOfTeams)
    numberOfTeams.innerHTML = "You are playing against 2 Teams"
    console.log(numberOfTeams)
}

const playingAgainstThreeTeam = function(){
    let numberOfTeams = document.getElementById("teamsPlayingPreview")
    // console.log(numberOfTeams)
    numberOfTeams.innerHTML = "You are playing against 3 Teams"
    console.log(numberOfTeams)
}


//managed to put 1 name from name list to team, and remove the name from name list afterwards 
//next step: turn this into a loop function and randomly assign names to group 
const assignNamesToGroups = function(){
    //get the array of Names generated by users
    let getAllNames = document.querySelectorAll("li")
    
    //get team 1 div
    //get the first name to team1
    let getTeam1Div = document.getElementById("team-NameList")
    getTeam1Div.innerText = getAllNames[0].innerHTML
    getAllNames[0].outerHTML = ""

    // for (names of getAllNames){
    //     getTeam1Div.appendChild(names.innerHTML)
            // console.log(names.innerHTML)
    
}

